export const metadata = {
  title: 'Privacy Policy — Accessibility Auditor',
}

export default function PrivacyPolicy() {
  const lastUpdated = 'April 22, 2026'
  const contactEmail = 'evanfoulk4@gmail.com'
  const appUrl = 'https://epsilon-xi.vercel.app'

  return (
    <main style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px', fontFamily: 'system-ui, sans-serif', lineHeight: 1.7, color: '#1a1a1a' }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>Privacy Policy</h1>
      <p style={{ color: '#666', marginBottom: 40 }}>Last updated: {lastUpdated}</p>

      <Section title="1. Who we are">
        <p>
          Accessibility Auditor (&quot;the App&quot;, &quot;we&quot;, &quot;us&quot;) is a Shopify application that scans your
          online store for WCAG 2.1 accessibility violations and generates AI-powered fix recommendations.
          The App is available at <a href={appUrl}>{appUrl}</a>.
        </p>
      </Section>

      <Section title="2. What data we collect">
        <p>We collect and store the minimum data required to provide the service:</p>
        <ul>
          <li><strong>Shop domain</strong> — e.g. <code>your-store.myshopify.com</code>. Used to identify your store and scope all data to your account.</li>
          <li><strong>Shopify access token</strong> — the OAuth token Shopify issues when you install the App. Stored encrypted (AES-256-GCM) in our database. Used to make API calls on your behalf (reading products and pages for context when generating fixes).</li>
          <li><strong>Audit results</strong> — a record of each accessibility scan: the URL audited, timestamp, violation counts, and the detailed violation data returned by the Axe-core scanner. Stored and associated with your shop.</li>
          <li><strong>AI fix proposals</strong> — fix suggestions generated by the Gemini AI model in response to audit violations. Stored and associated with your shop.</li>
        </ul>
        <p>
          We do <strong>not</strong> collect, store, or process any personal data about your customers.
          Audits scan publicly accessible page HTML — no customer login sessions, no order data,
          no payment information.
        </p>
      </Section>

      <Section title="3. How we use your data">
        <ul>
          <li>To run accessibility audits on your store&apos;s public-facing pages</li>
          <li>To display your audit history within the App</li>
          <li>To generate and store AI-powered fix recommendations</li>
          <li>To authenticate future requests from your Shopify admin (via the stored access token)</li>
        </ul>
        <p>We do not sell, rent, or share your data with third parties for marketing purposes.</p>
      </Section>

      <Section title="4. Third-party services">
        <p>The App uses the following third-party services to operate:</p>
        <ul>
          <li><strong>Supabase</strong> — database hosting for sessions, audit results, and fix proposals. Data is stored in the EU (Ireland) region. <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">Supabase Privacy Policy</a></li>
          <li><strong>Google Gemini API</strong> — AI model used to generate fix recommendations. Violation data (HTML snippets and CSS selectors from your store) is sent to Google&apos;s API to generate suggestions. <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google Privacy Policy</a></li>
          <li><strong>Vercel</strong> — application hosting and serverless functions. <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener noreferrer">Vercel Privacy Policy</a></li>
        </ul>
      </Section>

      <Section title="5. Data retention">
        <ul>
          <li><strong>Session tokens</strong> — retained for as long as the App is installed. Deleted immediately when you uninstall.</li>
          <li><strong>Audit results and fix proposals</strong> — retained for as long as the App is installed. Permanently deleted within 48 hours of uninstall (on receipt of Shopify&apos;s shop/redact webhook).</li>
        </ul>
      </Section>

      <Section title="6. Your rights (GDPR / CCPA)">
        <p>
          If you are located in the European Economic Area, UK, or California, you have the right to access,
          correct, or request deletion of your data. To exercise these rights, contact us at{' '}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.
        </p>
        <p>
          When you uninstall the App, Shopify notifies us via a mandatory webhook. We delete your access
          token immediately and permanently delete all remaining data (audits, fix proposals) within 48 hours.
        </p>
        <p>
          Because we hold no customer personal data, customer data requests (GDPR Article 15) and
          erasure requests (GDPR Article 17) submitted via Shopify result in an immediate acknowledgement
          with no further action required on our part.
        </p>
      </Section>

      <Section title="7. Security">
        <p>
          Shopify access tokens are encrypted at rest using AES-256-GCM before being stored in our database.
          All data is transmitted over TLS. We do not log access tokens, session data, or any credentials.
        </p>
      </Section>

      <Section title="8. Changes to this policy">
        <p>
          We may update this policy from time to time. When we do, we will update the &quot;Last updated&quot; date
          at the top of this page. Continued use of the App after changes constitutes acceptance of the
          updated policy.
        </p>
      </Section>

      <Section title="9. Contact">
        <p>
          Questions about this policy or your data? Email us at{' '}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.
        </p>
      </Section>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12, borderBottom: '1px solid #e5e5e5', paddingBottom: 8 }}>
        {title}
      </h2>
      {children}
    </section>
  )
}
