export const metadata = {
  title: 'Terms of Service — Accessibility Auditor',
}

export default function TermsOfService() {
  const lastUpdated = 'April 24, 2026'
  const contactEmail = 'evanfoulk4@gmail.com'
  const appUrl = 'https://epsilon-xi.vercel.app'

  return (
    <main style={{ maxWidth: 760, margin: '0 auto', padding: '48px 24px', fontFamily: 'system-ui, sans-serif', lineHeight: 1.7, color: '#1a1a1a' }}>
      <h1 style={{ fontSize: 32, fontWeight: 700, marginBottom: 8 }}>Terms of Service</h1>
      <p style={{ color: '#666', marginBottom: 40 }}>Last updated: {lastUpdated}</p>

      <Section title="1. Acceptance of terms">
        <p>
          By installing or using Accessibility Auditor (&quot;the App&quot;, &quot;we&quot;, &quot;us&quot;), available at{' '}
          <a href={appUrl}>{appUrl}</a>, you agree to be bound by these Terms of Service (&quot;Terms&quot;).
          If you do not agree to these Terms, do not install or use the App.
        </p>
        <p>
          These Terms apply to all merchants who install the App through the Shopify App Store.
        </p>
      </Section>

      <Section title="2. Description of service">
        <p>
          Accessibility Auditor is a Shopify application that scans your online store&apos;s public-facing
          pages for WCAG 2.1 accessibility violations and generates AI-powered fix recommendations using
          the Google Gemini API.
        </p>
        <p>
          The App is provided as a tool to assist you in identifying potential accessibility issues.
          It does not guarantee that your store will meet any particular legal accessibility standard,
          nor does it constitute legal advice.
        </p>
      </Section>

      <Section title="3. Eligibility">
        <p>
          You must have an active Shopify store and be authorized to install apps on that store to use
          the App. By accepting these Terms, you represent that you have the authority to bind your
          business to these Terms.
        </p>
      </Section>

      <Section title="4. Acceptable use">
        <p>You agree to use the App only for lawful purposes and in accordance with these Terms. You agree not to:</p>
        <ul>
          <li>Use the App to scan URLs that you do not own or have permission to audit</li>
          <li>Attempt to reverse-engineer, decompile, or extract source code from the App</li>
          <li>Use the App in any way that could damage, disable, or impair the App or its infrastructure</li>
          <li>Attempt to gain unauthorized access to any part of the App or its related systems</li>
          <li>Use automated scripts to trigger audits at a volume beyond normal use</li>
        </ul>
      </Section>

      <Section title="5. AI-generated content">
        <p>
          Fix recommendations produced by the App are generated by an AI model (Google Gemini) and are
          provided for informational purposes only. We do not guarantee the accuracy, completeness, or
          fitness for any particular purpose of AI-generated suggestions. You are solely responsible for
          reviewing, testing, and deciding whether to implement any suggested fix in your store.
        </p>
      </Section>

      <Section title="6. Intellectual property">
        <p>
          The App, including its code, design, and content (excluding your store data), is owned by us
          and protected by applicable intellectual property laws. These Terms do not grant you any rights
          to our intellectual property other than the limited right to use the App as described herein.
        </p>
        <p>
          Your store data (audit results, fix proposals generated from your store&apos;s content) remains yours.
          We use it solely to provide the service as described in our{' '}
          <a href="/privacy">Privacy Policy</a>.
        </p>
      </Section>

      <Section title="7. Disclaimer of warranties">
        <p>
          The App is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express
          or implied, including but not limited to implied warranties of merchantability, fitness for a
          particular purpose, or non-infringement.
        </p>
        <p>
          We do not warrant that the App will be uninterrupted, error-free, or that defects will be
          corrected. Accessibility auditing results may not be exhaustive — automated tools cannot detect
          all WCAG violations.
        </p>
      </Section>

      <Section title="8. Limitation of liability">
        <p>
          To the maximum extent permitted by applicable law, we shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages arising out of or related to your use
          of the App, including but not limited to loss of revenue, loss of data, or failure to meet any
          duty, even if we have been advised of the possibility of such damages.
        </p>
        <p>
          Our total liability to you for any claim arising out of or relating to these Terms or the App
          shall not exceed the amount you paid us in the twelve months preceding the claim (or $0 for a
          free app).
        </p>
      </Section>

      <Section title="9. Indemnification">
        <p>
          You agree to indemnify and hold us harmless from any claims, damages, losses, or expenses
          (including reasonable legal fees) arising out of your use of the App, your violation of these
          Terms, or your violation of any third-party rights.
        </p>
      </Section>

      <Section title="10. Termination">
        <p>
          You may stop using the App at any time by uninstalling it from your Shopify store.
          We reserve the right to suspend or terminate your access to the App at any time if you
          violate these Terms or if we discontinue the App.
        </p>
        <p>
          Upon termination, your data will be deleted as described in our{' '}
          <a href="/privacy">Privacy Policy</a>.
        </p>
      </Section>

      <Section title="11. Changes to these terms">
        <p>
          We may update these Terms from time to time. When we do, we will update the &quot;Last updated&quot;
          date at the top of this page. Continued use of the App after changes constitutes your
          acceptance of the updated Terms.
        </p>
      </Section>

      <Section title="12. Governing law">
        <p>
          These Terms are governed by and construed in accordance with the laws of the United States,
          without regard to its conflict of law provisions.
        </p>
      </Section>

      <Section title="13. Contact">
        <p>
          Questions about these Terms? Email us at{' '}
          <a href={`mailto:${contactEmail}`}>{contactEmail}</a>.
        </p>
      </Section>
    </main>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 40 }}>
      <h2 style={{ fontSize: 20, fontWeight: 600, marginBottom: 12, borderBottom: '1px solid #e5e5e5', paddingBottom: 8 }}>
        {title}
      </h2>
      {children}
    </section>
  )
}
